// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: habits.sql

package database

import (
	"context"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits(user_id, name, revenue)
VALUES (?, ?, ?)
RETURNING id, user_id, name, revenue
`

type CreateHabitParams struct {
	UserID  int64   `json:"user_id"`
	Name    string  `json:"name"`
	Revenue float64 `json:"revenue"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit, arg.UserID, arg.Name, arg.Revenue)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Revenue,
	)
	return i, err
}
