// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
)

type Action struct {
	ID     int64   `json:"id"`
	UserID int64   `json:"user_id"`
	Name   string  `json:"name"`
	Cost   float64 `json:"cost"`
}

type PerformedAction struct {
	ID        int64        `json:"id"`
	ActionID  int64        `json:"action_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID       int64           `json:"id"`
	Email    sql.NullString  `json:"email"`
	Password sql.NullString  `json:"password"`
	Balance  sql.NullFloat64 `json:"balance"`
}
