// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import ()

type User struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ManagerID int64  `json:"manager_id"`
}
