// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: actions.sql

package database

import (
	"context"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions(user_id, name, cost)
VALUES (?, ?, ?)
RETURNING id, user_id, name, cost
`

type CreateActionParams struct {
	UserID int64   `json:"user_id"`
	Name   string  `json:"name"`
	Cost   float64 `json:"cost"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction, arg.UserID, arg.Name, arg.Cost)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Cost,
	)
	return i, err
}
